name: ant
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Set up JDK 8
          uses: actions/setup-java@v2.1.0
          with:
              java-version: 8
              distribution: zulu
        - name: Build with Ant
          run: ant -noinput -buildfile build.xml build
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: extra-sorts-jar
            path: dist/ArrayV-Extra-Sorts.jar
