name: build
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Set up JDK 8
          uses: actions/setup-java@v2.1.0
          with:
              java-version: 8
              distribution: zulu
        - name: Build with Maven
          run: mvn clean install
        - name: Rename JAR
          run: mv target/ArrayV-Extra-Sorts-*.jar target/ArrayV-Extra-Sorts.jar
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: extra-sorts-jar
            path: target/ArrayV-Extra-Sorts.jar
